ec2 add

diff --git a/Jenkinsfile.txt b/Jenkinsfile.txt
--- a/Jenkinsfile.txt
+++ b/Jenkinsfile.txt
@@ -1,23 +1,43 @@
 pipeline {
     agent any
 
+    environment {
+        EC2_USER = 'ubuntu'
+        EC2_HOST = '3.107.235.199'
+        APP_DIR  = '/home/ubuntu/app'
+    }
+
     stages {
 
-        stage('Clone Repository') {
+        stage('Clean Workspace') {
+            steps {
+                deleteDir()
+            }
+        }
+
+        stage('Checkout Code') {
             steps {
                 git url: 'https://github.com/armanuralbyice/learnDev.git', branch: 'main'
             }
         }
 
-        stage('Stop Old Containers') {
+        stage('Copy to EC2') {
             steps {
-                sh 'docker compose down || true'
+                sh """
+                scp -r * ${EC2_USER}@${EC2_HOST}:${APP_DIR}
+                """
             }
         }
 
-        stage('Build & Deploy') {
+        stage('Deploy on EC2') {
             steps {
-                sh 'docker compose up --build -d'
+                sh """
+                ssh ${EC2_USER}@${EC2_HOST} '
+                    cd ${APP_DIR} &&
+                    docker compose down || true &&
+                    docker compose up --build -d
+                '
+                """
             }
         }
 
@@ -25,10 +45,10 @@ pipeline {
 
     post {
         success {
-            echo '🚀 Deployment Successful'
+            echo "🚀 Deployment Successful on EC2"
         }
         failure {
-            echo '❌ Build Failed'
+            echo "❌ Deployment Failed"
         }
     }
 }
